//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 11:45:45 PM PDT 
//


package org.tolven.plugin.repository.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncludeDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncludeDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pluginsRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="includeType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="default"/>
 *             &lt;enumeration value="overlay"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncludeDetail")
public class IncludeDetail {

    @XmlAttribute
    protected String pluginsRef;
    @XmlAttribute
    protected String includeType;

    /**
     * Gets the value of the pluginsRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPluginsRef() {
        return pluginsRef;
    }

    /**
     * Sets the value of the pluginsRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPluginsRef(String value) {
        this.pluginsRef = value;
    }

    /**
     * Gets the value of the includeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeType() {
        return includeType;
    }

    /**
     * Sets the value of the includeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeType(String value) {
        this.includeType = value;
    }

}
