//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 11:45:45 PM PDT 
//


package org.tolven.plugin.repository.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="info" type="{urn:tolven-org:plugins:1.0}InfoDetail" minOccurs="0"/>
 *         &lt;element name="plugin" type="{urn:tolven-org:plugins:1.0}PluginDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="property" type="{urn:tolven-org:plugins:1.0}PluginPropertyDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="constraint" type="{urn:tolven-org:plugins:1.0}ConstraintDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="includes" type="{urn:tolven-org:plugins:1.0}IncludesDetail" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "info",
    "plugin",
    "property",
    "constraint",
    "includes"
})
@XmlRootElement(name = "plugins")
public class Plugins {

    protected InfoDetail info;
    protected List<PluginDetail> plugin;
    protected List<PluginPropertyDetail> property;
    protected List<ConstraintDetail> constraint;
    protected IncludesDetail includes;

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link InfoDetail }
     *     
     */
    public InfoDetail getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoDetail }
     *     
     */
    public void setInfo(InfoDetail value) {
        this.info = value;
    }

    /**
     * Gets the value of the plugin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plugin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlugin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PluginDetail }
     * 
     * 
     */
    public List<PluginDetail> getPlugin() {
        if (plugin == null) {
            plugin = new ArrayList<PluginDetail>();
        }
        return this.plugin;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PluginPropertyDetail }
     * 
     * 
     */
    public List<PluginPropertyDetail> getProperty() {
        if (property == null) {
            property = new ArrayList<PluginPropertyDetail>();
        }
        return this.property;
    }

    /**
     * Gets the value of the constraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstraintDetail }
     * 
     * 
     */
    public List<ConstraintDetail> getConstraint() {
        if (constraint == null) {
            constraint = new ArrayList<ConstraintDetail>();
        }
        return this.constraint;
    }

    /**
     * Gets the value of the includes property.
     * 
     * @return
     *     possible object is
     *     {@link IncludesDetail }
     *     
     */
    public IncludesDetail getIncludes() {
        return includes;
    }

    /**
     * Sets the value of the includes property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncludesDetail }
     *     
     */
    public void setIncludes(IncludesDetail value) {
        this.includes = value;
    }

}
