package epHospitalOrders
 /* Tolven */
import java.util.*;
import org.tolven.trim.*;
import org.tolven.trim.ex.*;
import org.tolven.doc.entity.*;
import java.lang.Integer;
import org.tolven.app.entity.MenuStructure;
import org.tolven.app.entity.MenuData;
import org.tolven.app.bean.Mode;
import org.tolven.app.bean.Plan;
import org.tolven.core.entity.Status;
import org.tolven.logging.TolvenLogger;
import org.tolven.process.FDBCompute;

global org.tolven.app.AppEvalAdaptor app;
global Date now;

//Hospital Medication Orders

rule "Place ePrescription on active hospitalMedicationOrders list"
	when
		$msList: MenuStructure( path == "echr:patient:hospitalMedicationOrders:active" )
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:hospitalMedicationOrder" )
		$md: MenuData( menuStructure == $ms, actStatus=='active')		
	then
		app.info("Place ePrescription on hospitalMedicationOrder list");
		MenuData md = app.createReferenceMD( $md, $msList );		
end

rule "Place ePrescription on inactive hospitalMedicationOrders list"
	when
		$msList: MenuStructure( path == "echr:patient:hospitalMedicationOrders:inactive" )
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:hospitalMedicationOrder" )
		$md: MenuData( menuStructure == $ms, actStatus=='completed')		
	then
		app.info("Place ePrescription on inactive medication list");
		MenuData md = app.createReferenceMD( $md, $msList );		
end
rule "Place ePrescription on nullified hospitalMedicationOrders list"
	when
		$msList: MenuStructure( path == "echr:patient:hospitalMedicationOrders:nullified" )
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:hospitalMedicationOrder" )
		$md: MenuData( menuStructure == $ms, actStatus=='nullified')		
	then
		app.info("Place ePrescription on nullified medication list");
		MenuData md = app.createReferenceMD( $md, $msList );		
end
rule "Place ePrescription on suspended hospitalMedicationOrders list"
	when
		$msList: MenuStructure( path == "echr:patient:hospitalMedicationOrders:suspended" )
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:hospitalMedicationOrder" )
		$md: MenuData( menuStructure == $ms, actStatus=='suspended')		
	then
		app.info("Place ePrescription on suspended medication list");
		MenuData md = app.createReferenceMD( $md, $msList );		
end
rule "Place ePrescription on held hospitalMedicationOrders list"
	when
		$msList: MenuStructure( path == "echr:patient:hospitalMedicationOrders:held" )
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:hospitalMedicationOrder" )
		$md: MenuData( menuStructure == $ms, actStatus=='held')		
	then
		app.info("Place ePrescription on held medication list");
		MenuData md = app.createReferenceMD( $md, $msList );		
end
rule "Place ePrescription on discontinued hospitalMedicationOrders list"
	when
		$msList: MenuStructure( path == "echr:patient:hospitalMedicationOrders:discontinued" )
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:hospitalMedicationOrder" )
		$md: MenuData( menuStructure == $ms, actStatus=='discontinued')		
	then
		app.info("Place ePrescription on discontinued medication list");
		MenuData md = app.createReferenceMD( $md, $msList );		
end
rule "Place ePrescription on all Hospital Medication Orders  list"
	when
		$msList: MenuStructure( path == "echr:patient:hospitalMedicationOrders:all" )
		$ms: MenuStructure( role == "placeholder", path == "echr:patient:hospitalMedicationOrder" )
		$md: MenuData( menuStructure == $ms)		
	then
		app.info("Place ePrescription on all Hospital Medication Orders list");
		MenuData md = app.createReferenceMD( $md, $msList );		
end

rule "Place Medication on Hospital Medication Orders summary list"
	when
		$msMedication: MenuStructure( role == "placeholder", path == "echr:patient:hospitalMedicationOrder" )
		$mdMedication: MenuData( menuStructure == $msMedication, actStatus == 'active' )
	then
		// Add act to patient's Medication list
		app.createReferenceMD( $mdMedication, "echr:patient:summary:hmedsum" );
end