@echo off
set TOLVEN_USER=
echo TOLVEN_USER: %TOLVEN_USER%
set TOLVEN_REALM=
echo TOLVEN_REALM: %TOLVEN_REALM%
set TOLVEN_PASSWORD=
echo TOLVEN_PASSWORD: xxxxxxxx
set TOLVEN_CONFIG_DIR=
echo TOLVEN_CONFIG_DIR: %TOLVEN_CONFIG_DIR%
