#!/bin/bash

export TOLVEN_USER=
echo TOLVEN_USER: $TOLVEN_USER
export TOLVEN_REALM=
echo TOLVEN_REALM: $TOLVEN_REALM
export TOLVEN_PASSWORD==
echo TOLVEN_PASSWORD: xxxxxxxx
export TOLVEN_CONFIG_DIR=
echo TOLVEN_CONFIG: $TOLVEN_CONFIG_DIR
