//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BenefitsCoordinationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BenefitsCoordinationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PayerIdentification" type="{http://www.surescripts.com/messaging}PayerIDType" minOccurs="0"/>
 *         &lt;element name="PayerName" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="CardholderID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="CardholderName" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="GroupID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="EffectiveDate" type="{http://www.surescripts.com/messaging}DateType" minOccurs="0"/>
 *         &lt;element name="ExpirationDate" type="{http://www.surescripts.com/messaging}DateType" minOccurs="0"/>
 *         &lt;element name="Consent" type="{http://www.surescripts.com/messaging}ConsentType" minOccurs="0"/>
 *         &lt;element name="PBMMemberID" type="{http://www.surescripts.com/messaging}an..80" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BenefitsCoordinationType", propOrder = {
    "payerIdentification",
    "payerName",
    "cardholderID",
    "cardholderName",
    "groupID",
    "effectiveDate",
    "expirationDate",
    "consent",
    "pbmMemberID"
})
public class BenefitsCoordinationType implements Serializable{

    @XmlElement(name = "PayerIdentification")
    protected PayerIDType payerIdentification;
    @XmlElement(name = "PayerName")
    protected String payerName;
    @XmlElement(name = "CardholderID")
    protected String cardholderID;
    @XmlElement(name = "CardholderName")
    protected String cardholderName;
    @XmlElement(name = "GroupID")
    protected String groupID;
    @XmlElement(name = "EffectiveDate")
    protected String effectiveDate;
    @XmlElement(name = "ExpirationDate")
    protected String expirationDate;
    @XmlElement(name = "Consent")
    protected ConsentType consent;
    @XmlElement(name = "PBMMemberID")
    protected String pbmMemberID;

    /**
     * Gets the value of the payerIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link PayerIDType }
     *     
     */
    public PayerIDType getPayerIdentification() {
        return payerIdentification;
    }

    /**
     * Sets the value of the payerIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayerIDType }
     *     
     */
    public void setPayerIdentification(PayerIDType value) {
        this.payerIdentification = value;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the cardholderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderID() {
        return cardholderID;
    }

    /**
     * Sets the value of the cardholderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderID(String value) {
        this.cardholderID = value;
    }

    /**
     * Gets the value of the cardholderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderName() {
        return cardholderName;
    }

    /**
     * Sets the value of the cardholderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderName(String value) {
        this.cardholderName = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupID(String value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDate(String value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the consent property.
     * 
     * @return
     *     possible object is
     *     {@link ConsentType }
     *     
     */
    public ConsentType getConsent() {
        return consent;
    }

    /**
     * Sets the value of the consent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsentType }
     *     
     */
    public void setConsent(ConsentType value) {
        this.consent = value;
    }

    /**
     * Gets the value of the pbmMemberID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPBMMemberID() {
        return pbmMemberID;
    }

    /**
     * Sets the value of the pbmMemberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPBMMemberID(String value) {
        this.pbmMemberID = value;
    }

}
