//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.surescripts.com/messaging}NewRx"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}RefillRequest"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}RefillResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}RxChangeRequest"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}RxChangeResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}RxFill"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}CancelRx"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}CancelRxResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}RxHistoryRequest"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}RxHistoryResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}EligibilityRequest"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}EligibilityResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}Status"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}Error"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}Verify"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}DirectoryDownload"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}DirectoryDownloadResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}AddPharmacy"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}UpdatePharmacy"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}AddPrescriber"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}UpdatePrescriber"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}AddPrescriberResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}AddPrescriberLocation"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}UpdatePrescriberLocation"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}AddPrescriberLocationResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}AddProvider"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}UpdateProvider"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}GetPrescriber"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}GetPrescriberResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}GetPharmacy"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}GetPharmacyResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}GetProvider"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}GetProviderResponse"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}Resupp"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BodyType", propOrder = {
    "newRx",
    "refillRequest",
    "refillResponse",
    "rxChangeRequest",
    "rxChangeResponse",
    "rxFill",
    "cancelRx",
    "cancelRxResponse",
    "rxHistoryRequest",
    "rxHistoryResponse",
    "eligibilityRequest",
    "eligibilityResponse",
    "status",
    "error",
    "verify",
    "directoryDownload",
    "directoryDownloadResponse",
    "addPharmacy",
    "updatePharmacy",
    "addPrescriber",
    "updatePrescriber",
    "addPrescriberResponse",
    "addPrescriberLocation",
    "updatePrescriberLocation",
    "addPrescriberLocationResponse",
    "addProvider",
    "updateProvider",
    "getPrescriber",
    "getPrescriberResponse",
    "getPharmacy",
    "getPharmacyResponse",
    "getProvider",
    "getProviderResponse",
    "resupp"
})
public class BodyType implements Serializable{

    @XmlElement(name = "NewRx")
    protected NewRx newRx;
    @XmlElement(name = "RefillRequest")
    protected RefillRequest refillRequest;
    @XmlElement(name = "RefillResponse")
    protected RefillResponse refillResponse;
    @XmlElement(name = "RxChangeRequest")
    protected RxChangeRequest rxChangeRequest;
    @XmlElement(name = "RxChangeResponse")
    protected RxChangeResponse rxChangeResponse;
    @XmlElement(name = "RxFill")
    protected RxFill rxFill;
    @XmlElement(name = "CancelRx")
    protected CancelRx cancelRx;
    @XmlElement(name = "CancelRxResponse")
    protected CancelRxResponse cancelRxResponse;
    @XmlElement(name = "RxHistoryRequest")
    protected RxHistoryRequest rxHistoryRequest;
    @XmlElement(name = "RxHistoryResponse")
    protected RxHistoryResponse rxHistoryResponse;
    @XmlElement(name = "EligibilityRequest")
    protected EligibilityRequest eligibilityRequest;
    @XmlElement(name = "EligibilityResponse")
    protected EligibilityResponse eligibilityResponse;
    @XmlElement(name = "Status")
    protected Status status;
    @XmlElement(name = "Error")
    protected Error error;
    @XmlElement(name = "Verify")
    protected Verify verify;
    @XmlElement(name = "DirectoryDownload")
    protected DirectoryDownload directoryDownload;
    @XmlElement(name = "DirectoryDownloadResponse")
    protected DirectoryDownloadResponse directoryDownloadResponse;
    @XmlElement(name = "AddPharmacy")
    protected AddPharmacy addPharmacy;
    @XmlElement(name = "UpdatePharmacy")
    protected UpdatePharmacy updatePharmacy;
    @XmlElement(name = "AddPrescriber")
    protected AddPrescriber addPrescriber;
    @XmlElement(name = "UpdatePrescriber")
    protected UpdatePrescriber updatePrescriber;
    @XmlElement(name = "AddPrescriberResponse")
    protected AddPrescriberResponse addPrescriberResponse;
    @XmlElement(name = "AddPrescriberLocation")
    protected AddPrescriberLocation addPrescriberLocation;
    @XmlElement(name = "UpdatePrescriberLocation")
    protected UpdatePrescriberLocation updatePrescriberLocation;
    @XmlElement(name = "AddPrescriberLocationResponse")
    protected AddPrescriberLocationResponse addPrescriberLocationResponse;
    @XmlElement(name = "AddProvider")
    protected AddProvider addProvider;
    @XmlElement(name = "UpdateProvider")
    protected UpdateProvider updateProvider;
    @XmlElement(name = "GetPrescriber")
    protected GetPrescriber getPrescriber;
    @XmlElement(name = "GetPrescriberResponse")
    protected GetPrescriberResponse getPrescriberResponse;
    @XmlElement(name = "GetPharmacy")
    protected GetPharmacy getPharmacy;
    @XmlElement(name = "GetPharmacyResponse")
    protected GetPharmacyResponse getPharmacyResponse;
    @XmlElement(name = "GetProvider")
    protected GetProvider getProvider;
    @XmlElement(name = "GetProviderResponse")
    protected GetProviderResponse getProviderResponse;
    @XmlElement(name = "Resupp")
    protected Resupp resupp;

    /**
     * Gets the value of the newRx property.
     * 
     * @return
     *     possible object is
     *     {@link NewRx }
     *     
     */
    public NewRx getNewRx() {
        return newRx;
    }

    /**
     * Sets the value of the newRx property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewRx }
     *     
     */
    public void setNewRx(NewRx value) {
        this.newRx = value;
    }

    /**
     * Gets the value of the refillRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RefillRequest }
     *     
     */
    public RefillRequest getRefillRequest() {
        return refillRequest;
    }

    /**
     * Sets the value of the refillRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefillRequest }
     *     
     */
    public void setRefillRequest(RefillRequest value) {
        this.refillRequest = value;
    }

    /**
     * Gets the value of the refillResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RefillResponse }
     *     
     */
    public RefillResponse getRefillResponse() {
        return refillResponse;
    }

    /**
     * Sets the value of the refillResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefillResponse }
     *     
     */
    public void setRefillResponse(RefillResponse value) {
        this.refillResponse = value;
    }

    /**
     * Gets the value of the rxChangeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RxChangeRequest }
     *     
     */
    public RxChangeRequest getRxChangeRequest() {
        return rxChangeRequest;
    }

    /**
     * Sets the value of the rxChangeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxChangeRequest }
     *     
     */
    public void setRxChangeRequest(RxChangeRequest value) {
        this.rxChangeRequest = value;
    }

    /**
     * Gets the value of the rxChangeResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RxChangeResponse }
     *     
     */
    public RxChangeResponse getRxChangeResponse() {
        return rxChangeResponse;
    }

    /**
     * Sets the value of the rxChangeResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxChangeResponse }
     *     
     */
    public void setRxChangeResponse(RxChangeResponse value) {
        this.rxChangeResponse = value;
    }

    /**
     * Gets the value of the rxFill property.
     * 
     * @return
     *     possible object is
     *     {@link RxFill }
     *     
     */
    public RxFill getRxFill() {
        return rxFill;
    }

    /**
     * Sets the value of the rxFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxFill }
     *     
     */
    public void setRxFill(RxFill value) {
        this.rxFill = value;
    }

    /**
     * Gets the value of the cancelRx property.
     * 
     * @return
     *     possible object is
     *     {@link CancelRx }
     *     
     */
    public CancelRx getCancelRx() {
        return cancelRx;
    }

    /**
     * Sets the value of the cancelRx property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelRx }
     *     
     */
    public void setCancelRx(CancelRx value) {
        this.cancelRx = value;
    }

    /**
     * Gets the value of the cancelRxResponse property.
     * 
     * @return
     *     possible object is
     *     {@link CancelRxResponse }
     *     
     */
    public CancelRxResponse getCancelRxResponse() {
        return cancelRxResponse;
    }

    /**
     * Sets the value of the cancelRxResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelRxResponse }
     *     
     */
    public void setCancelRxResponse(CancelRxResponse value) {
        this.cancelRxResponse = value;
    }

    /**
     * Gets the value of the rxHistoryRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RxHistoryRequest }
     *     
     */
    public RxHistoryRequest getRxHistoryRequest() {
        return rxHistoryRequest;
    }

    /**
     * Sets the value of the rxHistoryRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxHistoryRequest }
     *     
     */
    public void setRxHistoryRequest(RxHistoryRequest value) {
        this.rxHistoryRequest = value;
    }

    /**
     * Gets the value of the rxHistoryResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RxHistoryResponse }
     *     
     */
    public RxHistoryResponse getRxHistoryResponse() {
        return rxHistoryResponse;
    }

    /**
     * Sets the value of the rxHistoryResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RxHistoryResponse }
     *     
     */
    public void setRxHistoryResponse(RxHistoryResponse value) {
        this.rxHistoryResponse = value;
    }

    /**
     * Gets the value of the eligibilityRequest property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityRequest }
     *     
     */
    public EligibilityRequest getEligibilityRequest() {
        return eligibilityRequest;
    }

    /**
     * Sets the value of the eligibilityRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityRequest }
     *     
     */
    public void setEligibilityRequest(EligibilityRequest value) {
        this.eligibilityRequest = value;
    }

    /**
     * Gets the value of the eligibilityResponse property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityResponse }
     *     
     */
    public EligibilityResponse getEligibilityResponse() {
        return eligibilityResponse;
    }

    /**
     * Sets the value of the eligibilityResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityResponse }
     *     
     */
    public void setEligibilityResponse(EligibilityResponse value) {
        this.eligibilityResponse = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link Error }
     *     
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link Error }
     *     
     */
    public void setError(Error value) {
        this.error = value;
    }

    /**
     * Gets the value of the verify property.
     * 
     * @return
     *     possible object is
     *     {@link Verify }
     *     
     */
    public Verify getVerify() {
        return verify;
    }

    /**
     * Sets the value of the verify property.
     * 
     * @param value
     *     allowed object is
     *     {@link Verify }
     *     
     */
    public void setVerify(Verify value) {
        this.verify = value;
    }

    /**
     * Gets the value of the directoryDownload property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryDownload }
     *     
     */
    public DirectoryDownload getDirectoryDownload() {
        return directoryDownload;
    }

    /**
     * Sets the value of the directoryDownload property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryDownload }
     *     
     */
    public void setDirectoryDownload(DirectoryDownload value) {
        this.directoryDownload = value;
    }

    /**
     * Gets the value of the directoryDownloadResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryDownloadResponse }
     *     
     */
    public DirectoryDownloadResponse getDirectoryDownloadResponse() {
        return directoryDownloadResponse;
    }

    /**
     * Sets the value of the directoryDownloadResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryDownloadResponse }
     *     
     */
    public void setDirectoryDownloadResponse(DirectoryDownloadResponse value) {
        this.directoryDownloadResponse = value;
    }

    /**
     * Gets the value of the addPharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link AddPharmacy }
     *     
     */
    public AddPharmacy getAddPharmacy() {
        return addPharmacy;
    }

    /**
     * Sets the value of the addPharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddPharmacy }
     *     
     */
    public void setAddPharmacy(AddPharmacy value) {
        this.addPharmacy = value;
    }

    /**
     * Gets the value of the updatePharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link UpdatePharmacy }
     *     
     */
    public UpdatePharmacy getUpdatePharmacy() {
        return updatePharmacy;
    }

    /**
     * Sets the value of the updatePharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdatePharmacy }
     *     
     */
    public void setUpdatePharmacy(UpdatePharmacy value) {
        this.updatePharmacy = value;
    }

    /**
     * Gets the value of the addPrescriber property.
     * 
     * @return
     *     possible object is
     *     {@link AddPrescriber }
     *     
     */
    public AddPrescriber getAddPrescriber() {
        return addPrescriber;
    }

    /**
     * Sets the value of the addPrescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddPrescriber }
     *     
     */
    public void setAddPrescriber(AddPrescriber value) {
        this.addPrescriber = value;
    }

    /**
     * Gets the value of the updatePrescriber property.
     * 
     * @return
     *     possible object is
     *     {@link UpdatePrescriber }
     *     
     */
    public UpdatePrescriber getUpdatePrescriber() {
        return updatePrescriber;
    }

    /**
     * Sets the value of the updatePrescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdatePrescriber }
     *     
     */
    public void setUpdatePrescriber(UpdatePrescriber value) {
        this.updatePrescriber = value;
    }

    /**
     * Gets the value of the addPrescriberResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AddPrescriberResponse }
     *     
     */
    public AddPrescriberResponse getAddPrescriberResponse() {
        return addPrescriberResponse;
    }

    /**
     * Sets the value of the addPrescriberResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddPrescriberResponse }
     *     
     */
    public void setAddPrescriberResponse(AddPrescriberResponse value) {
        this.addPrescriberResponse = value;
    }

    /**
     * Gets the value of the addPrescriberLocation property.
     * 
     * @return
     *     possible object is
     *     {@link AddPrescriberLocation }
     *     
     */
    public AddPrescriberLocation getAddPrescriberLocation() {
        return addPrescriberLocation;
    }

    /**
     * Sets the value of the addPrescriberLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddPrescriberLocation }
     *     
     */
    public void setAddPrescriberLocation(AddPrescriberLocation value) {
        this.addPrescriberLocation = value;
    }

    /**
     * Gets the value of the updatePrescriberLocation property.
     * 
     * @return
     *     possible object is
     *     {@link UpdatePrescriberLocation }
     *     
     */
    public UpdatePrescriberLocation getUpdatePrescriberLocation() {
        return updatePrescriberLocation;
    }

    /**
     * Sets the value of the updatePrescriberLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdatePrescriberLocation }
     *     
     */
    public void setUpdatePrescriberLocation(UpdatePrescriberLocation value) {
        this.updatePrescriberLocation = value;
    }

    /**
     * Gets the value of the addPrescriberLocationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AddPrescriberLocationResponse }
     *     
     */
    public AddPrescriberLocationResponse getAddPrescriberLocationResponse() {
        return addPrescriberLocationResponse;
    }

    /**
     * Sets the value of the addPrescriberLocationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddPrescriberLocationResponse }
     *     
     */
    public void setAddPrescriberLocationResponse(AddPrescriberLocationResponse value) {
        this.addPrescriberLocationResponse = value;
    }

    /**
     * Gets the value of the addProvider property.
     * 
     * @return
     *     possible object is
     *     {@link AddProvider }
     *     
     */
    public AddProvider getAddProvider() {
        return addProvider;
    }

    /**
     * Sets the value of the addProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddProvider }
     *     
     */
    public void setAddProvider(AddProvider value) {
        this.addProvider = value;
    }

    /**
     * Gets the value of the updateProvider property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateProvider }
     *     
     */
    public UpdateProvider getUpdateProvider() {
        return updateProvider;
    }

    /**
     * Sets the value of the updateProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateProvider }
     *     
     */
    public void setUpdateProvider(UpdateProvider value) {
        this.updateProvider = value;
    }

    /**
     * Gets the value of the getPrescriber property.
     * 
     * @return
     *     possible object is
     *     {@link GetPrescriber }
     *     
     */
    public GetPrescriber getGetPrescriber() {
        return getPrescriber;
    }

    /**
     * Sets the value of the getPrescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPrescriber }
     *     
     */
    public void setGetPrescriber(GetPrescriber value) {
        this.getPrescriber = value;
    }

    /**
     * Gets the value of the getPrescriberResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GetPrescriberResponse }
     *     
     */
    public GetPrescriberResponse getGetPrescriberResponse() {
        return getPrescriberResponse;
    }

    /**
     * Sets the value of the getPrescriberResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPrescriberResponse }
     *     
     */
    public void setGetPrescriberResponse(GetPrescriberResponse value) {
        this.getPrescriberResponse = value;
    }

    /**
     * Gets the value of the getPharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link GetPharmacy }
     *     
     */
    public GetPharmacy getGetPharmacy() {
        return getPharmacy;
    }

    /**
     * Sets the value of the getPharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPharmacy }
     *     
     */
    public void setGetPharmacy(GetPharmacy value) {
        this.getPharmacy = value;
    }

    /**
     * Gets the value of the getPharmacyResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GetPharmacyResponse }
     *     
     */
    public GetPharmacyResponse getGetPharmacyResponse() {
        return getPharmacyResponse;
    }

    /**
     * Sets the value of the getPharmacyResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetPharmacyResponse }
     *     
     */
    public void setGetPharmacyResponse(GetPharmacyResponse value) {
        this.getPharmacyResponse = value;
    }

    /**
     * Gets the value of the getProvider property.
     * 
     * @return
     *     possible object is
     *     {@link GetProvider }
     *     
     */
    public GetProvider getGetProvider() {
        return getProvider;
    }

    /**
     * Sets the value of the getProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetProvider }
     *     
     */
    public void setGetProvider(GetProvider value) {
        this.getProvider = value;
    }

    /**
     * Gets the value of the getProviderResponse property.
     * 
     * @return
     *     possible object is
     *     {@link GetProviderResponse }
     *     
     */
    public GetProviderResponse getGetProviderResponse() {
        return getProviderResponse;
    }

    /**
     * Sets the value of the getProviderResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetProviderResponse }
     *     
     */
    public void setGetProviderResponse(GetProviderResponse value) {
        this.getProviderResponse = value;
    }

    /**
     * Gets the value of the resupp property.
     * 
     * @return
     *     possible object is
     *     {@link Resupp }
     *     
     */
    public Resupp getResupp() {
        return resupp;
    }

    /**
     * Sets the value of the resupp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resupp }
     *     
     */
    public void setResupp(Resupp value) {
        this.resupp = value;
    }

}
