//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DirectoryInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectoryInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PortalID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="AccountID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="BackupPortalID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="FaxPortalName" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="ServiceLevel" type="{http://www.surescripts.com/messaging}n..4M"/>
 *         &lt;element name="DefaultLocationServiceLevel" type="{http://www.surescripts.com/messaging}n..4M" minOccurs="0"/>
 *         &lt;element name="ActiveStartTime" type="{http://www.surescripts.com/messaging}UtcDateType"/>
 *         &lt;element name="ActiveEndTime" type="{http://www.surescripts.com/messaging}UtcDateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectoryInformationType", propOrder = {
    "portalID",
    "accountID",
    "backupPortalID",
    "faxPortalName",
    "serviceLevel",
    "defaultLocationServiceLevel",
    "activeStartTime",
    "activeEndTime"
})
public class DirectoryInformationType implements Serializable{

    @XmlElement(name = "PortalID")
    protected String portalID;
    @XmlElement(name = "AccountID")
    protected String accountID;
    @XmlElement(name = "BackupPortalID")
    protected String backupPortalID;
    @XmlElement(name = "FaxPortalName")
    protected String faxPortalName;
    @XmlElement(name = "ServiceLevel", required = true)
    protected String serviceLevel;
    @XmlElement(name = "DefaultLocationServiceLevel")
    protected String defaultLocationServiceLevel;
    @XmlElement(name = "ActiveStartTime", required = true)
    protected String activeStartTime;
    @XmlElement(name = "ActiveEndTime", required = true)
    protected String activeEndTime;

    /**
     * Gets the value of the portalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortalID() {
        return portalID;
    }

    /**
     * Sets the value of the portalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortalID(String value) {
        this.portalID = value;
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountID(String value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the backupPortalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupPortalID() {
        return backupPortalID;
    }

    /**
     * Sets the value of the backupPortalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupPortalID(String value) {
        this.backupPortalID = value;
    }

    /**
     * Gets the value of the faxPortalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxPortalName() {
        return faxPortalName;
    }

    /**
     * Sets the value of the faxPortalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxPortalName(String value) {
        this.faxPortalName = value;
    }

    /**
     * Gets the value of the serviceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLevel() {
        return serviceLevel;
    }

    /**
     * Sets the value of the serviceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLevel(String value) {
        this.serviceLevel = value;
    }

    /**
     * Gets the value of the defaultLocationServiceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLocationServiceLevel() {
        return defaultLocationServiceLevel;
    }

    /**
     * Sets the value of the defaultLocationServiceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLocationServiceLevel(String value) {
        this.defaultLocationServiceLevel = value;
    }

    /**
     * Gets the value of the activeStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveStartTime() {
        return activeStartTime;
    }

    /**
     * Sets the value of the activeStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveStartTime(String value) {
        this.activeStartTime = value;
    }

    /**
     * Gets the value of the activeEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveEndTime() {
        return activeEndTime;
    }

    /**
     * Sets the value of the activeEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveEndTime(String value) {
        this.activeEndTime = value;
    }

}
