//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DirectoryPharmacyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectoryPharmacyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DirectoryInformation" type="{http://www.surescripts.com/messaging}DirectoryInformationType" minOccurs="0"/>
 *         &lt;element name="Identification" type="{http://www.surescripts.com/messaging}PharmacyIDType"/>
 *         &lt;element name="StoreName" type="{http://www.surescripts.com/messaging}an..35M"/>
 *         &lt;element name="StoreNumber" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="Pharmacist" type="{http://www.surescripts.com/messaging}DirectoryNameType" minOccurs="0"/>
 *         &lt;element name="PharmacistAgent" type="{http://www.surescripts.com/messaging}DirectoryNameType" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://www.surescripts.com/messaging}MandatoryAddressType" minOccurs="0"/>
 *         &lt;element name="TwentyFourHourFlag" type="{http://www.surescripts.com/messaging}TwentyFourHourFlagType" minOccurs="0"/>
 *         &lt;element name="CrossStreet" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://www.surescripts.com/messaging}an..80" minOccurs="0"/>
 *         &lt;element name="PhoneNumbers" type="{http://www.surescripts.com/messaging}PhoneNumbersType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectoryPharmacyType", propOrder = {
    "directoryInformation",
    "identification",
    "storeName",
    "storeNumber",
    "pharmacist",
    "pharmacistAgent",
    "address",
    "twentyFourHourFlag",
    "crossStreet",
    "email",
    "phoneNumbers"
})
public class DirectoryPharmacyType implements Serializable{

    @XmlElement(name = "DirectoryInformation")
    protected DirectoryInformationType directoryInformation;
    @XmlElement(name = "Identification", required = true)
    protected PharmacyIDType identification;
    @XmlElement(name = "StoreName", required = true)
    protected String storeName;
    @XmlElement(name = "StoreNumber")
    protected String storeNumber;
    @XmlElement(name = "Pharmacist")
    protected DirectoryNameType pharmacist;
    @XmlElement(name = "PharmacistAgent")
    protected DirectoryNameType pharmacistAgent;
    @XmlElement(name = "Address")
    protected MandatoryAddressType address;
    @XmlElement(name = "TwentyFourHourFlag")
    protected String twentyFourHourFlag;
    @XmlElement(name = "CrossStreet")
    protected String crossStreet;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "PhoneNumbers", required = true)
    protected PhoneNumbersType phoneNumbers;

    /**
     * Gets the value of the directoryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryInformationType }
     *     
     */
    public DirectoryInformationType getDirectoryInformation() {
        return directoryInformation;
    }

    /**
     * Sets the value of the directoryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryInformationType }
     *     
     */
    public void setDirectoryInformation(DirectoryInformationType value) {
        this.directoryInformation = value;
    }

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link PharmacyIDType }
     *     
     */
    public PharmacyIDType getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmacyIDType }
     *     
     */
    public void setIdentification(PharmacyIDType value) {
        this.identification = value;
    }

    /**
     * Gets the value of the storeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * Sets the value of the storeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreName(String value) {
        this.storeName = value;
    }

    /**
     * Gets the value of the storeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoreNumber() {
        return storeNumber;
    }

    /**
     * Sets the value of the storeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoreNumber(String value) {
        this.storeNumber = value;
    }

    /**
     * Gets the value of the pharmacist property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryNameType }
     *     
     */
    public DirectoryNameType getPharmacist() {
        return pharmacist;
    }

    /**
     * Sets the value of the pharmacist property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryNameType }
     *     
     */
    public void setPharmacist(DirectoryNameType value) {
        this.pharmacist = value;
    }

    /**
     * Gets the value of the pharmacistAgent property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryNameType }
     *     
     */
    public DirectoryNameType getPharmacistAgent() {
        return pharmacistAgent;
    }

    /**
     * Sets the value of the pharmacistAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryNameType }
     *     
     */
    public void setPharmacistAgent(DirectoryNameType value) {
        this.pharmacistAgent = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link MandatoryAddressType }
     *     
     */
    public MandatoryAddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatoryAddressType }
     *     
     */
    public void setAddress(MandatoryAddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the twentyFourHourFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwentyFourHourFlag() {
        return twentyFourHourFlag;
    }

    /**
     * Sets the value of the twentyFourHourFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwentyFourHourFlag(String value) {
        this.twentyFourHourFlag = value;
    }

    /**
     * Gets the value of the crossStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrossStreet() {
        return crossStreet;
    }

    /**
     * Sets the value of the crossStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrossStreet(String value) {
        this.crossStreet = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the phoneNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneNumbersType }
     *     
     */
    public PhoneNumbersType getPhoneNumbers() {
        return phoneNumbers;
    }

    /**
     * Sets the value of the phoneNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneNumbersType }
     *     
     */
    public void setPhoneNumbers(PhoneNumbersType value) {
        this.phoneNumbers = value;
    }

}
