//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DirectoryDataProviderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectoryDataProviderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DirectoryInformation" type="{http://www.surescripts.com/messaging}DataProviderDirectoryInformationType" minOccurs="0"/>
 *         &lt;element name="Identification" type="{http://www.surescripts.com/messaging}DataProviderIDType"/>
 *         &lt;element name="Description" type="{http://www.surescripts.com/messaging}an..255M"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectoryDataProviderType", propOrder = {
    "directoryInformation",
    "identification",
    "description"
})
public class DirectoryDataProviderType implements Serializable{

    @XmlElement(name = "DirectoryInformation")
    protected DataProviderDirectoryInformationType directoryInformation;
    @XmlElement(name = "Identification", required = true)
    protected DataProviderIDType identification;
    @XmlElement(name = "Description", required = true)
    protected String description;

    /**
     * Gets the value of the directoryInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DataProviderDirectoryInformationType }
     *     
     */
    public DataProviderDirectoryInformationType getDirectoryInformation() {
        return directoryInformation;
    }

    /**
     * Sets the value of the directoryInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProviderDirectoryInformationType }
     *     
     */
    public void setDirectoryInformation(DataProviderDirectoryInformationType value) {
        this.directoryInformation = value;
    }

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link DataProviderIDType }
     *     
     */
    public DataProviderIDType getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataProviderIDType }
     *     
     */
    public void setIdentification(DataProviderIDType value) {
        this.identification = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
