//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountID" type="{http://www.surescripts.com/messaging}an..35"/>
 *         &lt;element name="VersionID" type="{http://www.surescripts.com/messaging}VersionIDType"/>
 *         &lt;element name="Taxonomy" type="{http://www.surescripts.com/messaging}TaxonomyType"/>
 *         &lt;element name="DirectoryDate" type="{http://www.surescripts.com/messaging}DateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountID",
    "versionID",
    "taxonomy",
    "directoryDate"
})
@XmlRootElement(name = "DirectoryDownload")
public class DirectoryDownload implements Serializable{

    @XmlElement(name = "AccountID", required = true)
    protected String accountID;
    @XmlElement(name = "VersionID", required = true)
    protected String versionID;
    @XmlElement(name = "Taxonomy", required = true)
    protected TaxonomyType taxonomy;
    @XmlElement(name = "DirectoryDate")
    protected String directoryDate;

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountID(String value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the versionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionID() {
        return versionID;
    }

    /**
     * Sets the value of the versionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionID(String value) {
        this.versionID = value;
    }

    /**
     * Gets the value of the taxonomy property.
     * 
     * @return
     *     possible object is
     *     {@link TaxonomyType }
     *     
     */
    public TaxonomyType getTaxonomy() {
        return taxonomy;
    }

    /**
     * Sets the value of the taxonomy property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxonomyType }
     *     
     */
    public void setTaxonomy(TaxonomyType value) {
        this.taxonomy = value;
    }

    /**
     * Gets the value of the directoryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectoryDate() {
        return directoryDate;
    }

    /**
     * Sets the value of the directoryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectoryDate(String value) {
        this.directoryDate = value;
    }

}
