//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DrugCodedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DrugCodedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductCode" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="ProductCodeQualifier" type="{http://www.surescripts.com/messaging}an..3" minOccurs="0"/>
 *         &lt;element name="DosageForm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="01|02|03|04|05|06|07|10|11|12|13|14|15|16|20|21|22|23|24|25|30|31|32|33|34|40|41|42|43|50|52|53|60|61|62|63|64|65|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|98|99|100|101|102|103|104|105|106|107|108|109|111|112|113|114|115|116|117|118|119|120|121|122|123|124|125|126|127|128|129|130|131|132|133|134|135|136|137|138|139|140|141|142|143|144|145|146|147|148|149|150|151|152|153|154|155|156|157|158|159|160|161|162|163|164"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Strength" type="{http://www.surescripts.com/messaging}an..70" minOccurs="0"/>
 *         &lt;element name="StrengthUnits" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="00|10|12|14|1N|22|23|3F|40|41|4E|4G|4M|58|60|93|AF|AM|AQ|AR|AS|AU|AV|AW|AY|BG|BI|BO|BX|C3|C5|C7|C8|CC|CH|CI|CM|CQ|CS|CT|CU|D5|DA|DB|DD|DF|DG|DI|DJ|DL|E8|EA|EC|EP|EQ|F2|F3|F4|F5|FG|FH|FO|FZ|GA|GB|GC|GE|GF|GH|GI|GJ|GK|GL|GM|GO|GP|GQ|GR|GX|H2|H4|HP|HR|HT|IH|IN|JR|KC|KD|KE|KG|KI|KM|KT|KW|KX|L2|LB|LQ|LT|M1|M2|M7|MC|ME|ML|MM|MO|MR|MS|MX|MY|MZ|N1|N4|N9|NA|NX|OP|OZ|P1|P3|P4|P5|P6|P7|P8|P9|PH|PK|PR|PT|PV|PX|PY|Q2|QK|QS|QT|QU|S1|S2|SR|SZ|T2|TB|TP|TY|U1|U2|U3|U5|UM|UN|UP|UQ|UR|US|UT|UU|UV|UW|UX|VI|VP|VS|WW|X4|X9|Y2|Y3|Y4|Y5|Y6|Y7|Y8|Y9|Y10|Y11|Y12|YR|ZZ"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DrugDBCode" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="DrugDBCodeQualifier" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="E|G|FG|FS|MC|MD|MG|MM|SCD|SBD|BPC|GPC"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrugCodedType", propOrder = {
    "productCode",
    "productCodeQualifier",
    "dosageForm",
    "strength",
    "strengthUnits",
    "drugDBCode",
    "drugDBCodeQualifier"
})
public class DrugCodedType implements Serializable{

    @XmlElement(name = "ProductCode")
    protected String productCode;
    @XmlElement(name = "ProductCodeQualifier")
    protected String productCodeQualifier;
    @XmlElement(name = "DosageForm")
    protected String dosageForm;
    @XmlElement(name = "Strength")
    protected String strength;
    @XmlElement(name = "StrengthUnits")
    protected String strengthUnits;
    @XmlElement(name = "DrugDBCode")
    protected String drugDBCode;
    @XmlElement(name = "DrugDBCodeQualifier")
    protected String drugDBCodeQualifier;

    /**
     * Gets the value of the productCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * Sets the value of the productCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCode(String value) {
        this.productCode = value;
    }

    /**
     * Gets the value of the productCodeQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCodeQualifier() {
        return productCodeQualifier;
    }

    /**
     * Sets the value of the productCodeQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCodeQualifier(String value) {
        this.productCodeQualifier = value;
    }

    /**
     * Gets the value of the dosageForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDosageForm() {
        return dosageForm;
    }

    /**
     * Sets the value of the dosageForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDosageForm(String value) {
        this.dosageForm = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrength(String value) {
        this.strength = value;
    }

    /**
     * Gets the value of the strengthUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrengthUnits() {
        return strengthUnits;
    }

    /**
     * Sets the value of the strengthUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrengthUnits(String value) {
        this.strengthUnits = value;
    }

    /**
     * Gets the value of the drugDBCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugDBCode() {
        return drugDBCode;
    }

    /**
     * Sets the value of the drugDBCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugDBCode(String value) {
        this.drugDBCode = value;
    }

    /**
     * Gets the value of the drugDBCodeQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrugDBCodeQualifier() {
        return drugDBCodeQualifier;
    }

    /**
     * Sets the value of the drugDBCodeQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrugDBCodeQualifier(String value) {
        this.drugDBCodeQualifier = value;
    }

}
