//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Response" type="{http://www.surescripts.com/messaging}EligibilityResponseType"/>
 *         &lt;element name="Source" type="{http://www.surescripts.com/messaging}ResponseSourceType"/>
 *         &lt;element name="Receiver" type="{http://www.surescripts.com/messaging}ResponseReceiverType"/>
 *         &lt;element name="Patient" type="{http://www.surescripts.com/messaging}EligibilityResponsePatientType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "source",
    "receiver",
    "patient"
})
@XmlRootElement(name = "EligibilityResponse")
public class EligibilityResponse implements Serializable{

    @XmlElement(name = "Response", required = true)
    protected EligibilityResponseType response;
    @XmlElement(name = "Source", required = true)
    protected ResponseSourceType source;
    @XmlElement(name = "Receiver", required = true)
    protected ResponseReceiverType receiver;
    @XmlElement(name = "Patient", required = true)
    protected EligibilityResponsePatientType patient;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityResponseType }
     *     
     */
    public EligibilityResponseType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityResponseType }
     *     
     */
    public void setResponse(EligibilityResponseType value) {
        this.response = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseSourceType }
     *     
     */
    public ResponseSourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseSourceType }
     *     
     */
    public void setSource(ResponseSourceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseReceiverType }
     *     
     */
    public ResponseReceiverType getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseReceiverType }
     *     
     */
    public void setReceiver(ResponseReceiverType value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityResponsePatientType }
     *     
     */
    public EligibilityResponsePatientType getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityResponsePatientType }
     *     
     */
    public void setPatient(EligibilityResponsePatientType value) {
        this.patient = value;
    }

}
