//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FillStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FillStatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Filled" type="{http://www.surescripts.com/messaging}FillNoteType"/>
 *         &lt;element name="NotFilled" type="{http://www.surescripts.com/messaging}DeniedFillType"/>
 *         &lt;element name="PartialFill" type="{http://www.surescripts.com/messaging}FillNoteType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FillStatusType", propOrder = {
    "filled",
    "notFilled",
    "partialFill"
})
public class FillStatusType implements Serializable{

    @XmlElement(name = "Filled")
    protected FillNoteType filled;
    @XmlElement(name = "NotFilled")
    protected DeniedFillType notFilled;
    @XmlElement(name = "PartialFill")
    protected FillNoteType partialFill;

    /**
     * Gets the value of the filled property.
     * 
     * @return
     *     possible object is
     *     {@link FillNoteType }
     *     
     */
    public FillNoteType getFilled() {
        return filled;
    }

    /**
     * Sets the value of the filled property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillNoteType }
     *     
     */
    public void setFilled(FillNoteType value) {
        this.filled = value;
    }

    /**
     * Gets the value of the notFilled property.
     * 
     * @return
     *     possible object is
     *     {@link DeniedFillType }
     *     
     */
    public DeniedFillType getNotFilled() {
        return notFilled;
    }

    /**
     * Sets the value of the notFilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeniedFillType }
     *     
     */
    public void setNotFilled(DeniedFillType value) {
        this.notFilled = value;
    }

    /**
     * Gets the value of the partialFill property.
     * 
     * @return
     *     possible object is
     *     {@link FillNoteType }
     *     
     */
    public FillNoteType getPartialFill() {
        return partialFill;
    }

    /**
     * Sets the value of the partialFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillNoteType }
     *     
     */
    public void setPartialFill(FillNoteType value) {
        this.partialFill = value;
    }

}
