//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Observation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Observation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MeasurementType" type="{http://www.surescripts.com/messaging}an..3"/>
 *         &lt;element name="MeasurementValue" type="{http://www.surescripts.com/messaging}n..18M"/>
 *         &lt;element name="MeasureQualifier" type="{http://www.surescripts.com/messaging}an..3"/>
 *         &lt;element name="ObservationDate" type="{http://www.surescripts.com/messaging}UtcDateType"/>
 *         &lt;element name="ObservationQualifier" type="{http://www.surescripts.com/messaging}an..3"/>
 *         &lt;element name="MeasurementDataQualifier" type="{http://www.surescripts.com/messaging}an..3"/>
 *         &lt;element name="ObservationNotes" type="{http://www.surescripts.com/messaging}an..70" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Observation", propOrder = {
    "measurementType",
    "measurementValue",
    "measureQualifier",
    "observationDate",
    "observationQualifier",
    "measurementDataQualifier",
    "observationNotes"
})
public class Observation implements Serializable{

    @XmlElement(name = "MeasurementType", required = true)
    protected String measurementType;
    @XmlElement(name = "MeasurementValue", required = true)
    protected String measurementValue;
    @XmlElement(name = "MeasureQualifier", required = true)
    protected String measureQualifier;
    @XmlElement(name = "ObservationDate", required = true)
    protected String observationDate;
    @XmlElement(name = "ObservationQualifier", required = true)
    protected String observationQualifier;
    @XmlElement(name = "MeasurementDataQualifier", required = true)
    protected String measurementDataQualifier;
    @XmlElement(name = "ObservationNotes")
    protected String observationNotes;

    /**
     * Gets the value of the measurementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementType() {
        return measurementType;
    }

    /**
     * Sets the value of the measurementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementType(String value) {
        this.measurementType = value;
    }

    /**
     * Gets the value of the measurementValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementValue() {
        return measurementValue;
    }

    /**
     * Sets the value of the measurementValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementValue(String value) {
        this.measurementValue = value;
    }

    /**
     * Gets the value of the measureQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureQualifier() {
        return measureQualifier;
    }

    /**
     * Sets the value of the measureQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureQualifier(String value) {
        this.measureQualifier = value;
    }

    /**
     * Gets the value of the observationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationDate() {
        return observationDate;
    }

    /**
     * Sets the value of the observationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationDate(String value) {
        this.observationDate = value;
    }

    /**
     * Gets the value of the observationQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationQualifier() {
        return observationQualifier;
    }

    /**
     * Sets the value of the observationQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationQualifier(String value) {
        this.observationQualifier = value;
    }

    /**
     * Gets the value of the measurementDataQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementDataQualifier() {
        return measurementDataQualifier;
    }

    /**
     * Sets the value of the measurementDataQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementDataQualifier(String value) {
        this.measurementDataQualifier = value;
    }

    /**
     * Gets the value of the observationNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationNotes() {
        return observationNotes;
    }

    /**
     * Sets the value of the observationNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationNotes(String value) {
        this.observationNotes = value;
    }

}
