//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.surescripts.com/messaging", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tolven.surescripts;
