//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatientLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FacilityUnit" type="{http://www.surescripts.com/messaging}an..35"/>
 *         &lt;element name="PatientRoom" type="{http://www.surescripts.com/messaging}an..10"/>
 *         &lt;element name="PatientBed" type="{http://www.surescripts.com/messaging}an..10"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientLocation", propOrder = {
    "facilityUnit",
    "patientRoom",
    "patientBed"
})
public class PatientLocation implements Serializable{

    @XmlElement(name = "FacilityUnit", required = true)
    protected String facilityUnit;
    @XmlElement(name = "PatientRoom", required = true)
    protected String patientRoom;
    @XmlElement(name = "PatientBed", required = true)
    protected String patientBed;

    /**
     * Gets the value of the facilityUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityUnit() {
        return facilityUnit;
    }

    /**
     * Sets the value of the facilityUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityUnit(String value) {
        this.facilityUnit = value;
    }

    /**
     * Gets the value of the patientRoom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientRoom() {
        return patientRoom;
    }

    /**
     * Sets the value of the patientRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientRoom(String value) {
        this.patientRoom = value;
    }

    /**
     * Gets the value of the patientBed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientBed() {
        return patientBed;
    }

    /**
     * Sets the value of the patientBed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientBed(String value) {
        this.patientBed = value;
    }

}
