//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="GenericSubstitution" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="TherapeuticInterchangeSubstitution" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="PriorAuthorizationRequired" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "genericSubstitution",
    "therapeuticInterchangeSubstitution",
    "priorAuthorizationRequired"
})
public class RequestType implements Serializable{

    @XmlElement(name = "GenericSubstitution")
    protected Object genericSubstitution;
    @XmlElement(name = "TherapeuticInterchangeSubstitution")
    protected Object therapeuticInterchangeSubstitution;
    @XmlElement(name = "PriorAuthorizationRequired")
    protected Object priorAuthorizationRequired;

    /**
     * Gets the value of the genericSubstitution property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGenericSubstitution() {
        return genericSubstitution;
    }

    /**
     * Sets the value of the genericSubstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGenericSubstitution(Object value) {
        this.genericSubstitution = value;
    }

    /**
     * Gets the value of the therapeuticInterchangeSubstitution property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTherapeuticInterchangeSubstitution() {
        return therapeuticInterchangeSubstitution;
    }

    /**
     * Sets the value of the therapeuticInterchangeSubstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTherapeuticInterchangeSubstitution(Object value) {
        this.therapeuticInterchangeSubstitution = value;
    }

    /**
     * Gets the value of the priorAuthorizationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getPriorAuthorizationRequired() {
        return priorAuthorizationRequired;
    }

    /**
     * Sets the value of the priorAuthorizationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setPriorAuthorizationRequired(Object value) {
        this.priorAuthorizationRequired = value;
    }

}
