//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.surescripts.com/messaging}Approved" minOccurs="0"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}Denied" minOccurs="0"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}DeniedNewPrescriptionToFollow" minOccurs="0"/>
 *         &lt;element ref="{http://www.surescripts.com/messaging}ApprovedWithChanges" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseType", propOrder = {
    "approved",
    "denied",
    "deniedNewPrescriptionToFollow",
    "approvedWithChanges"
})
public class ResponseType implements Serializable {

    @XmlElement(name = "Approved")
    protected Approved approved;
    @XmlElement(name = "Denied")
    protected Denied denied;
    @XmlElement(name = "DeniedNewPrescriptionToFollow")
    protected DeniedNewPrescriptionToFollow deniedNewPrescriptionToFollow;
    @XmlElement(name = "ApprovedWithChanges")
    protected ApprovedWithChanges approvedWithChanges;

    /**
     * Gets the value of the approved property.
     * 
     * @return
     *     possible object is
     *     {@link Approved }
     *     
     */
    public Approved getApproved() {
        return approved;
    }

    /**
     * Sets the value of the approved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Approved }
     *     
     */
    public void setApproved(Approved value) {
        this.approved = value;
    }

    /**
     * Gets the value of the denied property.
     * 
     * @return
     *     possible object is
     *     {@link Denied }
     *     
     */
    public Denied getDenied() {
        return denied;
    }

    /**
     * Sets the value of the denied property.
     * 
     * @param value
     *     allowed object is
     *     {@link Denied }
     *     
     */
    public void setDenied(Denied value) {
        this.denied = value;
    }

    /**
     * Gets the value of the deniedNewPrescriptionToFollow property.
     * 
     * @return
     *     possible object is
     *     {@link DeniedNewPrescriptionToFollow }
     *     
     */
    public DeniedNewPrescriptionToFollow getDeniedNewPrescriptionToFollow() {
        return deniedNewPrescriptionToFollow;
    }

    /**
     * Sets the value of the deniedNewPrescriptionToFollow property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeniedNewPrescriptionToFollow }
     *     
     */
    public void setDeniedNewPrescriptionToFollow(DeniedNewPrescriptionToFollow value) {
        this.deniedNewPrescriptionToFollow = value;
    }

    /**
     * Gets the value of the approvedWithChanges property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovedWithChanges }
     *     
     */
    public ApprovedWithChanges getApprovedWithChanges() {
        return approvedWithChanges;
    }

    /**
     * Sets the value of the approvedWithChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovedWithChanges }
     *     
     */
    public void setApprovedWithChanges(ApprovedWithChanges value) {
        this.approvedWithChanges = value;
    }

}
