//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FacilityRxReferenceNumber" type="{http://www.surescripts.com/messaging}an..35M"/>
 *         &lt;element name="RxReferenceNumber" type="{http://www.surescripts.com/messaging}an..35M"/>
 *         &lt;element name="RelatesToMessageID" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="PrescriberOrderNumber" type="{http://www.surescripts.com/messaging}an..35" minOccurs="0"/>
 *         &lt;element name="Pharmacy" type="{http://www.surescripts.com/messaging}MandatoryPharmacyType"/>
 *         &lt;element name="Prescriber" type="{http://www.surescripts.com/messaging}PrescriberType"/>
 *         &lt;element name="Facility" type="{http://www.surescripts.com/messaging}FacilityType"/>
 *         &lt;element name="Patient" type="{http://www.surescripts.com/messaging}PatientType"/>
 *         &lt;element name="RelationToCardHolder" type="{http://www.surescripts.com/messaging}RelationToCardHolder"/>
 *         &lt;element name="PatientLocation" type="{http://www.surescripts.com/messaging}PatientLocation"/>
 *         &lt;element name="Benefits" type="{http://www.surescripts.com/messaging}Benefit"/>
 *         &lt;element name="MedicationPrescribed" type="{http://www.surescripts.com/messaging}MedicationPrescribedType"/>
 *         &lt;element name="MedicationDispensed" type="{http://www.surescripts.com/messaging}MedicationPrescribedType"/>
 *         &lt;element name="Observations" type="{http://www.surescripts.com/messaging}Observations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "facilityRxReferenceNumber",
    "rxReferenceNumber",
    "relatesToMessageID",
    "prescriberOrderNumber",
    "pharmacy",
    "prescriber",
    "facility",
    "patient",
    "relationToCardHolder",
    "patientLocation",
    "benefits",
    "medicationPrescribed",
    "medicationDispensed",
    "observations"
})
@XmlRootElement(name = "Resupp")
public class Resupp implements Serializable {

    @XmlElement(name = "FacilityRxReferenceNumber", required = true)
    protected String facilityRxReferenceNumber;
    @XmlElement(name = "RxReferenceNumber", required = true)
    protected String rxReferenceNumber;
    @XmlElement(name = "RelatesToMessageID")
    protected String relatesToMessageID;
    @XmlElement(name = "PrescriberOrderNumber")
    protected String prescriberOrderNumber;
    @XmlElement(name = "Pharmacy", required = true)
    protected MandatoryPharmacyType pharmacy;
    @XmlElement(name = "Prescriber", required = true)
    protected PrescriberType prescriber;
    @XmlElement(name = "Facility", required = true)
    protected FacilityType facility;
    @XmlElement(name = "Patient", required = true)
    protected PatientType patient;
    @XmlElement(name = "RelationToCardHolder", required = true)
    protected String relationToCardHolder;
    @XmlElement(name = "PatientLocation", required = true)
    protected PatientLocation patientLocation;
    @XmlElement(name = "Benefits", required = true)
    protected Benefit benefits;
    @XmlElement(name = "MedicationPrescribed", required = true)
    protected MedicationPrescribedType medicationPrescribed;
    @XmlElement(name = "MedicationDispensed", required = true)
    protected MedicationPrescribedType medicationDispensed;
    @XmlElement(name = "Observations", required = true)
    protected Observations observations;

    /**
     * Gets the value of the facilityRxReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityRxReferenceNumber() {
        return facilityRxReferenceNumber;
    }

    /**
     * Sets the value of the facilityRxReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityRxReferenceNumber(String value) {
        this.facilityRxReferenceNumber = value;
    }

    /**
     * Gets the value of the rxReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRxReferenceNumber() {
        return rxReferenceNumber;
    }

    /**
     * Sets the value of the rxReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRxReferenceNumber(String value) {
        this.rxReferenceNumber = value;
    }

    /**
     * Gets the value of the relatesToMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatesToMessageID() {
        return relatesToMessageID;
    }

    /**
     * Sets the value of the relatesToMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatesToMessageID(String value) {
        this.relatesToMessageID = value;
    }

    /**
     * Gets the value of the prescriberOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriberOrderNumber() {
        return prescriberOrderNumber;
    }

    /**
     * Sets the value of the prescriberOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriberOrderNumber(String value) {
        this.prescriberOrderNumber = value;
    }

    /**
     * Gets the value of the pharmacy property.
     * 
     * @return
     *     possible object is
     *     {@link MandatoryPharmacyType }
     *     
     */
    public MandatoryPharmacyType getPharmacy() {
        return pharmacy;
    }

    /**
     * Sets the value of the pharmacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatoryPharmacyType }
     *     
     */
    public void setPharmacy(MandatoryPharmacyType value) {
        this.pharmacy = value;
    }

    /**
     * Gets the value of the prescriber property.
     * 
     * @return
     *     possible object is
     *     {@link PrescriberType }
     *     
     */
    public PrescriberType getPrescriber() {
        return prescriber;
    }

    /**
     * Sets the value of the prescriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrescriberType }
     *     
     */
    public void setPrescriber(PrescriberType value) {
        this.prescriber = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityType }
     *     
     */
    public FacilityType getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityType }
     *     
     */
    public void setFacility(FacilityType value) {
        this.facility = value;
    }

    /**
     * Gets the value of the patient property.
     * 
     * @return
     *     possible object is
     *     {@link PatientType }
     *     
     */
    public PatientType getPatient() {
        return patient;
    }

    /**
     * Sets the value of the patient property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientType }
     *     
     */
    public void setPatient(PatientType value) {
        this.patient = value;
    }

    /**
     * Gets the value of the relationToCardHolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationToCardHolder() {
        return relationToCardHolder;
    }

    /**
     * Sets the value of the relationToCardHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationToCardHolder(String value) {
        this.relationToCardHolder = value;
    }

    /**
     * Gets the value of the patientLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PatientLocation }
     *     
     */
    public PatientLocation getPatientLocation() {
        return patientLocation;
    }

    /**
     * Sets the value of the patientLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientLocation }
     *     
     */
    public void setPatientLocation(PatientLocation value) {
        this.patientLocation = value;
    }

    /**
     * Gets the value of the benefits property.
     * 
     * @return
     *     possible object is
     *     {@link Benefit }
     *     
     */
    public Benefit getBenefits() {
        return benefits;
    }

    /**
     * Sets the value of the benefits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Benefit }
     *     
     */
    public void setBenefits(Benefit value) {
        this.benefits = value;
    }

    /**
     * Gets the value of the medicationPrescribed property.
     * 
     * @return
     *     possible object is
     *     {@link MedicationPrescribedType }
     *     
     */
    public MedicationPrescribedType getMedicationPrescribed() {
        return medicationPrescribed;
    }

    /**
     * Sets the value of the medicationPrescribed property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicationPrescribedType }
     *     
     */
    public void setMedicationPrescribed(MedicationPrescribedType value) {
        this.medicationPrescribed = value;
    }

    /**
     * Gets the value of the medicationDispensed property.
     * 
     * @return
     *     possible object is
     *     {@link MedicationPrescribedType }
     *     
     */
    public MedicationPrescribedType getMedicationDispensed() {
        return medicationDispensed;
    }

    /**
     * Sets the value of the medicationDispensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedicationPrescribedType }
     *     
     */
    public void setMedicationDispensed(MedicationPrescribedType value) {
        this.medicationDispensed = value;
    }

    /**
     * Gets the value of the observations property.
     * 
     * @return
     *     possible object is
     *     {@link Observations }
     *     
     */
    public Observations getObservations() {
        return observations;
    }

    /**
     * Sets the value of the observations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Observations }
     *     
     */
    public void setObservations(Observations value) {
        this.observations = value;
    }

}
