//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 11:44:06 AM GMT+05:30 
//


package org.tolven.surescripts;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecialtyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialtyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Qualifier">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="AM|DE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SpecialtyCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="AS|ADM|ADP|AMI|ADL|OAR|AM|A|AI|PTH|ATP|AN|BBK|CTS|CD|PCH|CHP|CHN|PLI|DDL|ALI|ILI|CBG|ICE|CCG|CG|CMG|CN|CLP|PA|CRS|CCA|CCM|NCC|OCC|PCP|DS|D|DMP|DIA|DR|EM|END|EP|FPS|FP|OFA|FOP|PFP|GE|GP|GPM|GS|FPG|IMG|PYG|GO|GYN|HS|HNS|HEM|HMP|HO|HEP|IG|PIP|ID|IM|MPD|LM|MFM|MXR|MG|MDM|MM|ON|ETX|PDT|PTX|OMO|NPM|NEP|NS|N|NRN|NP|RNR|NM|NR|NTR|OBS|OBG|OM|OPH|ORS|OSS|OTR|OMM|OS|OTO|OT|APM|PMD|PLM|PDA|PDC|CCP|PE|PEM|PDE|PG|PHO|PDI|PN|PO|OP|PDO|PP|PDP|PDR|PPR|NSP|PDS|UP|PD|PM|PS|PRO|P|PYA|MPH|PUD|PCC|RO|RIP|RP|R|REN|RHU|SP|SM|SCI|ESM|FSM|ISM|OSM|PSM|CCS|SO|TTS|TRS|UM|US|U|VIR|VS"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialtyType", propOrder = {
    "qualifier",
    "specialtyCode"
})
public class SpecialtyType implements Serializable{

    @XmlElement(name = "Qualifier", required = true)
    protected String qualifier;
    @XmlElement(name = "SpecialtyCode", required = true)
    protected String specialtyCode;

    /**
     * Gets the value of the qualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifier() {
        return qualifier;
    }

    /**
     * Sets the value of the qualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifier(String value) {
        this.qualifier = value;
    }

    /**
     * Gets the value of the specialtyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialtyCode() {
        return specialtyCode;
    }

    /**
     * Sets the value of the specialtyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialtyCode(String value) {
        this.specialtyCode = value;
    }

}
