
package org.tolven.client.examples.ws.trim.jaxws;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "trim", targetNamespace = "http://tolven.org/trim")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Trim {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "displayInstantiatedTrim", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.DisplayInstantiatedTrim")
    @ResponseWrapper(localName = "displayInstantiatedTrimResponse", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.DisplayInstantiatedTrimResponse")
    public void displayInstantiatedTrim(
        @WebParam(name = "arg0", targetNamespace = "")
        TolvenMessageWithAttachments arg0);

    /**
     * 
     */
    @WebMethod(action = "logout")
    @RequestWrapper(localName = "logout", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.LogoutResponse")
    public void logout();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "submitMessage", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.SubmitMessage")
    @ResponseWrapper(localName = "submitMessageResponse", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.SubmitMessageResponse")
    public void submitMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        TolvenMessageWithAttachments arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns org.tolven.client.examples.ws.trim.jaxws.TolvenMessageWithAttachments
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTolvenMessage", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.CreateTolvenMessage")
    @ResponseWrapper(localName = "createTolvenMessageResponse", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.CreateTolvenMessageResponse")
    public TolvenMessageWithAttachments createTolvenMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2);

    /**
     * 
     * @param webServiceTrim
     */
    @WebMethod(action = "submitTrim")
    @Oneway
    @RequestWrapper(localName = "submitTrim", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.SubmitTrim")
    public void submitTrim(
        @WebParam(name = "webServiceTrim", targetNamespace = "")
        WebServiceTrim webServiceTrim);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addTrimAsPayload", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.AddTrimAsPayload")
    @ResponseWrapper(localName = "addTrimAsPayloadResponse", targetNamespace = "http://tolven.org/trim", className = "org.tolven.client.examples.ws.trim.jaxws.AddTrimAsPayloadResponse")
    public void addTrimAsPayload(
        @WebParam(name = "arg0", targetNamespace = "")
        Trim_Type arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        TolvenMessage arg1);

}
