
package org.tolven.client.examples.ws.trim.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TrimService", targetNamespace = "http://tolven.org/trim", wsdlLocation = "http://dev.able.com:8080/ws/trim?wsdl")
public class TrimService
    extends Service
{

    private final static URL TRIMSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRIMSERVICE_EXCEPTION;
    private final static QName TRIMSERVICE_QNAME = new QName("http://tolven.org/trim", "TrimService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev.able.com:8080/ws/trim?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRIMSERVICE_WSDL_LOCATION = url;
        TRIMSERVICE_EXCEPTION = e;
    }

    public TrimService() {
        super(__getWsdlLocation(), TRIMSERVICE_QNAME);
    }

    public TrimService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRIMSERVICE_QNAME, features);
    }

    public TrimService(URL wsdlLocation) {
        super(wsdlLocation, TRIMSERVICE_QNAME);
    }

    public TrimService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRIMSERVICE_QNAME, features);
    }

    public TrimService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrimService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Trim
     */
    @WebEndpoint(name = "trimPort")
    public Trim getTrimPort() {
        return super.getPort(new QName("http://tolven.org/trim", "trimPort"), Trim.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Trim
     */
    @WebEndpoint(name = "trimPort")
    public Trim getTrimPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tolven.org/trim", "trimPort"), Trim.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRIMSERVICE_EXCEPTION!= null) {
            throw TRIMSERVICE_EXCEPTION;
        }
        return TRIMSERVICE_WSDL_LOCATION;
    }

}
