package base_echr_patient_personal_event
// See http://wiki.tolven.org/doc/index.php/Plugin:org.tolven.component.tolvenejb#PlaceholderFacts
// for details on the following annotation:

 /* Tolven */
import java.util.*;
import org.tolven.trim.*;
import org.tolven.trim.ex.*;
import org.tolven.doc.entity.*;
import java.lang.Integer;
import org.tolven.app.entity.MenuStructure;
import org.tolven.app.entity.MenuData;
import org.tolven.app.bean.Mode;
import org.tolven.app.bean.Plan;
import org.tolven.core.entity.Status;
import org.tolven.doc.bean.TolvenMessage;
import org.tolven.model.Patient;
import org.tolven.trim.process.ProcessTrim;

global org.tolven.app.AppEvalAdaptor app;
global Date now;

rule "Place Personal Event on Personal Event list"
	when
		$msPEvent: MenuStructure( role == "placeholder", path == "echr:patient:personalEvent" )
		$msList: MenuStructure( role == "list", path == "echr:patient:personalEvents:all" )
		$mdPEvent: MenuData( menuStructure == $msPEvent, actStatus == "active" )
	then
		app.createReferenceMD( $mdPEvent, $msList );
end

rule "Place Personal Event on summary list"
	when
		$msPEvent: MenuStructure( role == "placeholder", path == "echr:patient:personalEvent" )
		$msList: MenuStructure( role == "list", path == "echr:patient:summary:pevnsum" )
		$mdPEvent: MenuData( menuStructure == $msPEvent, actStatus == "active" )
	then
		MenuData md = app.createReferenceMD( $mdPEvent, $msList );
end


