/*
 * PostgresqlConnectionPanel.java
 *
 * Created on June 23, 2009, 1:58 PM
 */

package org.tolven.surescripts.postgresqlmgr.gui;

import java.awt.Cursor;

import javax.swing.JOptionPane;

import org.tolven.surescripts.postgresqlmgr.PostgresqlMgr;

/**
 *
 * @author  Joseph Isaac
 */
public class PostgresqlConnectionPanel extends javax.swing.JPanel {

    private PostgresqlMgr postgresqlMgr;

    /**
     * Creates new form PostgresqlConnectionPanel
     */
    public PostgresqlConnectionPanel(PostgresqlMgr postgresqlMgr) {
        initComponents();
        this.postgresqlMgr = postgresqlMgr;
        hostnameTextField.setText(postgresqlMgr.getHostname());
        portTextField.setText(postgresqlMgr.getPort());
        databaseNameTextField.setText(postgresqlMgr.getDBName());
        databaseUserTextField.setText(postgresqlMgr.getDBRootUser());
        configurationLabel.setText(postgresqlMgr.getDBId() + " Configuration");
        adminDBLabel.setText(postgresqlMgr.getAdminId() + " To " + postgresqlMgr.getDBId() + " Connection:");
        simulatedAppServerLabel.setText("Simulated " + postgresqlMgr.getAppServerId() + " To " + postgresqlMgr.getDBId() + " Connection:");
    }

    private void testAdminDBConnection() {
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String result = postgresqlMgr.testAdminDBConnection();
            JOptionPane.showMessageDialog(getRootPane(), result);
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }

    private void testSimulatedAppServerDBConnection() {
        try {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            String result = postgresqlMgr.testSimulatedAppServerDBConnection();
            JOptionPane.showMessageDialog(getRootPane(), result);
        } finally {
            setCursor(Cursor.getDefaultCursor());
        }
    }

    private String getNestedMessage(Exception ex) {
        StringBuffer buff = new StringBuffer();
        Throwable throwable = ex;
        do {
            buff.append(throwable.getMessage() + "\n");
            throwable = throwable.getCause();
        } while (throwable != null);
        return buff.toString();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        configurationLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hostnameTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        databaseNameTextField = new javax.swing.JTextField();
        databaseUserTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        adminDBLabel = new javax.swing.JLabel();
        testAdminDBButton = new javax.swing.JButton();
        simulatedAppServerLabel = new javax.swing.JLabel();
        testAppServerDBButton = new javax.swing.JButton();

        configurationLabel.setText("DB Configuration");

        jLabel4.setText("Hostname:");

        jLabel5.setText("Port:");

        jLabel6.setText("Database Name:");

        jLabel7.setText("Database User:");

        hostnameTextField.setEditable(false);

        portTextField.setEditable(false);

        databaseNameTextField.setEditable(false);

        databaseUserTextField.setEditable(false);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(configurationLabel)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(hostnameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(portTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(databaseNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(databaseUserTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {jLabel4, jLabel5, jLabel6, jLabel7}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(configurationLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hostnameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(portTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(databaseNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(databaseUserTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminDBLabel.setText("Admin To DB Connection:");

        testAdminDBButton.setText("Test");
        testAdminDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testAdminDBButtonActionPerformed(evt);
            }
        });

        simulatedAppServerLabel.setText("Simulated AppServer To DB Connection:");

        testAppServerDBButton.setText("Test");
        testAppServerDBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testAppServerDBButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(adminDBLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testAdminDBButton))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(simulatedAppServerLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testAppServerDBButton)))
                .addContainerGap(459, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(new java.awt.Component[] {adminDBLabel, simulatedAppServerLabel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(adminDBLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(testAdminDBButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(simulatedAppServerLabel)
                    .add(testAppServerDBButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void testAdminDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testAdminDBButtonActionPerformed
        try {
            testAdminDBConnection();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(getRootPane(), getNestedMessage(ex));
        }
}//GEN-LAST:event_testAdminDBButtonActionPerformed

    private void testAppServerDBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testAppServerDBButtonActionPerformed
        try {
            testSimulatedAppServerDBConnection();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(getRootPane(), getNestedMessage(ex));
        }
}//GEN-LAST:event_testAppServerDBButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminDBLabel;
    private javax.swing.JLabel configurationLabel;
    private javax.swing.JTextField databaseNameTextField;
    private javax.swing.JTextField databaseUserTextField;
    private javax.swing.JTextField hostnameTextField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField portTextField;
    private javax.swing.JLabel simulatedAppServerLabel;
    private javax.swing.JButton testAdminDBButton;
    private javax.swing.JButton testAppServerDBButton;
    // End of variables declaration//GEN-END:variables

}
