package echrasthma
// See http://wiki.tolven.org/doc/index.php/Plugin:org.tolven.component.tolvenejb#PlaceholderFacts
// for details on the following annotation:
//@use echr placeholders

 /* Tolven */
import java.util.*;
import java.lang.Integer;
import org.tolven.app.entity.MenuStructure;
import org.tolven.app.entity.MenuData;
import org.tolven.model.Patient;
import org.tolven.app.bean.PatientFact;

global org.tolven.app.AppEvalAdaptor app;
global Date now;

import function org.tolven.trim.contstants.PatientImportance.isVIP;

// THESE ARE THE OLD RULES.  I LEFT THEM AROUND FOR HISTORICAL PURPOSES BUT THEY ARE REPLACED BY THE TWO
// RULES BELOW 
//rule "Add Asthma problem to Asthma patient list"
//	when
//		$ms: MenuStructure( role == "placeholder", path == "echr:patient:problem" )
//		$md: MenuData( menuStructure == $ms, actStatus!="nullified", 
//			$dxName: string01 matches "(?i).*asthma.*", $mdPat : parent01 )
//		$msList: MenuStructure( path == "echr:patients:asthma" )
//		eval( !isVIP($mdPat.getField( "vip")) )
//	then
//		app.createReferenceMD( $mdPat, $msList );
//end

//rule "Add Asthma Diagnosis to Asthma patient list"
//	when
//		$ms: MenuStructure( role == "placeholder", path == "echr:patient:diagnosis" )
//		$md: MenuData( menuStructure == $ms, actStatus!="nullified", 
//			$dxName: string01 matches ".*Asthma.*", $mdPat : parent01 )
//		$msList: MenuStructure( path == "echr:patients:asthma" )
//	then
//		app.createReferenceMD( $mdPat, $msList );
//end

rule "Determine if patient has a asthma problem"
  when
    $msPatient: MenuStructure( role == "placeholder", path == "echr:patient" )
    $msProblemList: MenuStructure( path == "echr:patient:problems:active" )
    $mdPatient: MenuData( menuStructure == $msPatient)
    eval( app.onList($mdPatient, $msProblemList, "lower(string01) like '%asthma%'") )
  then
    insert (new PatientFact( $mdPatient, "asthmaProblem"));
end

rule "Put patient on asthma list if patient has a asthma problem"
  when
    $msPatient: MenuStructure( role == "placeholder", path == "echr:patient" )
    $mdPatient: MenuData( menuStructure == $msPatient)
    PatientFact( name=="asthmaProblem", patient==$mdPatient ) 
    $msList: MenuStructure( role == "list", path == "echr:patients:asthma" )
  then
    app.createReferenceMD( $mdPatient, $msList);
end

