
package org.tolven.client.examples.ws.document.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "document", targetNamespace = "http://tolven.org/document")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Document {


    /**
     * 
     * @param ns
     * @param accountId
     * @param payload
     * @return
     *     returns long
     */
    @WebMethod(action = "processDocument")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processDocument", targetNamespace = "http://tolven.org/document", className = "org.tolven.client.examples.ws.document.jaxws.ProcessDocument")
    @ResponseWrapper(localName = "processDocumentResponse", targetNamespace = "http://tolven.org/document", className = "org.tolven.client.examples.ws.document.jaxws.ProcessDocumentResponse")
    public long processDocument(
        @WebParam(name = "payload", targetNamespace = "")
        byte[] payload,
        @WebParam(name = "ns", targetNamespace = "")
        String ns,
        @WebParam(name = "accountId", targetNamespace = "")
        long accountId);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "test")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://tolven.org/document", className = "org.tolven.client.examples.ws.document.jaxws.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://tolven.org/document", className = "org.tolven.client.examples.ws.document.jaxws.TestResponse")
    public String test();

    /**
     * 
     * @param ns
     * @param accountId
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "queueMessage")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queueMessage", targetNamespace = "http://tolven.org/document", className = "org.tolven.client.examples.ws.document.jaxws.QueueMessage")
    @ResponseWrapper(localName = "queueMessageResponse", targetNamespace = "http://tolven.org/document", className = "org.tolven.client.examples.ws.document.jaxws.QueueMessageResponse")
    public String queueMessage(
        @WebParam(name = "payload", targetNamespace = "")
        byte[] payload,
        @WebParam(name = "ns", targetNamespace = "")
        String ns,
        @WebParam(name = "accountId", targetNamespace = "")
        long accountId);

    /**
     * 
     */
    @WebMethod(action = "logout")
    @RequestWrapper(localName = "logout", targetNamespace = "http://tolven.org/document", className = "org.tolven.client.examples.ws.document.jaxws.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://tolven.org/document", className = "org.tolven.client.examples.ws.document.jaxws.LogoutResponse")
    public void logout();

}
