
package org.tolven.client.examples.ws.generator.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GeneratorService", targetNamespace = "http://tolven.org/generator", wsdlLocation = "http://dev.able.com:8080/ws/generator?wsdl")
public class GeneratorService
    extends Service
{

    private final static URL GENERATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERATORSERVICE_EXCEPTION;
    private final static QName GENERATORSERVICE_QNAME = new QName("http://tolven.org/generator", "GeneratorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dev.able.com:8080/ws/generator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERATORSERVICE_WSDL_LOCATION = url;
        GENERATORSERVICE_EXCEPTION = e;
    }

    public GeneratorService() {
        super(__getWsdlLocation(), GENERATORSERVICE_QNAME);
    }

    public GeneratorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERATORSERVICE_QNAME, features);
    }

    public GeneratorService(URL wsdlLocation) {
        super(wsdlLocation, GENERATORSERVICE_QNAME);
    }

    public GeneratorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERATORSERVICE_QNAME, features);
    }

    public GeneratorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneratorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Generator
     */
    @WebEndpoint(name = "generatorPort")
    public Generator getGeneratorPort() {
        return super.getPort(new QName("http://tolven.org/generator", "generatorPort"), Generator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Generator
     */
    @WebEndpoint(name = "generatorPort")
    public Generator getGeneratorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tolven.org/generator", "generatorPort"), Generator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERATORSERVICE_EXCEPTION!= null) {
            throw GENERATORSERVICE_EXCEPTION;
        }
        return GENERATORSERVICE_WSDL_LOCATION;
    }

}
