INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('00', 'Not Specified');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('12', 'Packet');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('AR', 'Suppository');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('AV', 'Capsule');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('BG', 'Bag');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('BO', 'Bottle');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('BX', 'Box');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('CH', 'Container');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('CQ', 'Catridge');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('EA', 'Each');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('F2', 'International Unite');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('FO', 'Fluid Ounce');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('GR', 'Gram');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('FG', 'Transdermal Patch');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('IH', 'Inhaler');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('KT', 'Kit');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('LT', 'Liter');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('ME', 'Milligram');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('ML', 'Millileter');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('PH', 'Pack');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('PT', 'Pint');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('SZ', 'Syringe');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('TB', 'Tube');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('U2', 'Tablet');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('UM', 'Million Units');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('UN', 'Unit');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('UU', 'Lozenge');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('VI', 'Vial');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('X4', 'Drop');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('Y2', 'Tablespoon');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('Y3', 'Teaspoon');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('Y7', 'Gum');
INSERT INTO app.drug_qualifiers (qualcode, qualdesc) VALUES ('ZZ', 'Mutually Defined');
