INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (000 ,'SCRIPT Validation Error: See free text for description');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (001 ,'Sender ID not on file.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (002 ,'Receiver ID not on file.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (003 ,' Invalid password for sender.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (004 ,' Invalid password for receiver');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (005 ,' No password on file for sender.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (006 ,' No password on file for receiver.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (007 ,' Internal processing error has occurred.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (008 ,' Request timed out before response could be received.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (009 ,' Required segment UIB is missing.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (010 ,' Required segment UIH is missing.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (011 ,' Required segment UIT is missing.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (012 ,' Required segment UIZ is missing.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (013 ,' Unknown segment has been encountered.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (014 ,' Too many UIB segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (015 ,' Too many UIH segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (016 ,' Too many UIT segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (017 ,' Too many UIZ segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (018 ,' Password is blank.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (019 ,' Too many segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (020 ,' Unknown data element encountered.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (021 ,' Unsupported version in message.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (022 ,' Unsupported release in message.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (023 ,' Error found in an unused field.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (024 ,'Message ending problem.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (025 ,' UIB trace number is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (026 ,' UIB initiator reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (027 ,' UIB control agency is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (028 ,' UIB sender identification is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (029 ,' UIB date is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (030 ,' UIB time is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (031 ,' UIB time offset is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (032 ,' UIB duplicate flag is invalid. Also being used as “message is a duplicate” for interim. DERF numeration is pending.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (033 ,' UIB test flag is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (034 ,' UIH message type is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (035 ,' UIH function is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (036 ,' UIH association code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (037 ,' UIH prescription number is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (038 ,' UIH initiator reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (039 ,' UIH initiator reference identifier isinvalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (040 ,' UIH control agency is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (041 ,' UIH responder control reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (042 ,' REQ message function is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (043 ,' REQ reason code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (044 ,' REQ reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (045 ,' REQ old password is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (046 ,' REQ new password is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (047 ,' RES response type is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (048 ,' RES response code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (049 ,' RES reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (050 ,' RES free text is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (051 ,' STS status code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (052 ,' STS reject code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (053 ,' STS free text is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (054 ,' PVD provider type is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (055 ,' PVD reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (056 ,' PVD reference qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (057 ,' PVD agency qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (058 ,' PVD specialty code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (059 ,' PVD prescriber last name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (060 ,' PVD prescriber first name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (061 ,' PVD prescriber middle name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (062 ,' PVD prescriber name suffix is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (063 ,' PVD prescriber name prefix is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (064 ,' PVD prescriber postal code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (065 ,' PVD clinic name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (066 ,' PVD clinic street is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (067 ,' PVD clinic city is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (068 ,' PVD clinic country is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (069 ,' PVD clinic postal code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (070 ,' PVD clinic place qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (071 ,' PVD clinic place name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (072 ,' PVD communication reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (073 ,' PVD communication qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (074 ,' PVD agent last name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (075 ,' PVD agent first name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (076 ,' PVD agent middle name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (077 ,' PVD agent name suffix is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (078 ,' PVD agent name prefix is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (079 ,' PTT patient relationship is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (080 ,' PTT patient birth date is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (081 ,' PTT patient last name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (082 ,' PTT patient first name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (083 ,' PTT patient middle name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (084 ,' PTT patient name suffix is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (085 ,' PTT patient name prefix is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (086 ,' PTT patient gender is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (087 ,' PTT patient reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (088 ,' PTT patient reference qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (089 ,' PTT patient street is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (090 ,' PTT patient city is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (091 ,' PTT patient country is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (092 ,' PTT patient postal code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (093 ,' PTT patient place qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (094 ,' PTT patient place name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (095 ,' PTT communication reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (096 ,' PTT communication reference qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (097 ,' COO payer reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (098 ,' COO payer reference qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (099 ,' COO payer name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (100 ,' COO service type is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (101 ,' COO cardholder reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (102 ,' COO cardholder reference qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (103 ,' COO cardholder name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (104 ,' COO group reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (105 ,' COO group name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (106 ,' COO group street is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (107 ,' COO group city is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (108 ,' COO group country is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (109 ,' COO group postal code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (110 ,' COO group place qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (111 ,' COO group place name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (112 ,' COO date time qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (113 ,' COO date time is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (114 ,' COO date time format qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (115 ,' COO insurance type is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (116 ,' COO holder street is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (117 ,' COO holder city is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (118 ,' COO holder country is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (119 ,' COO holder postal code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (120 ,' COO holder place qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (121 ,' COO holder place name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (122 ,' COO holder reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (123 ,' COO holder reference qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (124 ,' COO response code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (125 ,' DRU drug disposition code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (126 ,' DRU drug name is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (127 ,' DRU drug item number is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (128 ,' DRU drug agency is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (129 ,' DRU drug agency qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (130 ,' DRU drug strength is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (131 ,' DRU drug strength qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (132 ,' DRU drug reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (133 ,' DRU drug reference qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (134 ,' DRU dosage quantity qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (135 ,' DRU dosage quantity is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (136 ,' DRU dosage info qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (137 ,' DRU dosage info is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (138 ,' DRU dosage free text is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (139 ,' DRU date time qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (140 ,' DRU date time is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (141 ,' DRU date time format qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (142 ,' DRU substitution code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (143 ,' DRU refill quantity qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (144 ,' DRU refill quantity is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (145 ,' DRU clinical info qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (146 ,' DRU clinical info level1 reference is invalid');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (147 ,' DRU clinical info level1 qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (148 ,' DRU clinical info level2 reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (149 ,' DRU clinical info level2 qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (150 ,' DRU prior authorization reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (151 ,' DRU prior authorization qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (152 ,' DRU free text is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (153 ,' OBS measurement dimension is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (154 ,' OBS measurement value is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (155 ,' OBS measurement qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (156 ,' OBS date time is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (157 ,' OBS date time qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (158 ,' OBS free text is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (159 ,' UIT reference number is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (160 ,' UIT segment count is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (161 ,' UIZ dial reference is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (162 ,' UIZ dial identifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (163 ,' UIZ control agency is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (164 ,' UIZ responder control ref is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (165 ,' UIZ message count is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (166 ,' Too many elements in COO segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (167 ,' Too many elements in DRU segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (168 ,' Too many elements in OBS segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (169 ,' Too many elements in PTT segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (170 ,' Too many elements in PVD segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (171 ,' Too many elements in REQ segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (172 ,' Too many elements in RES segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (173 ,' Too many elements in STS segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (174 ,' Too many elements in UIB segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (175 ,' Too many elements in UIH segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (176 ,' Too many elements in UIT segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (177 ,' Too many elements in UIZ segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (178 ,' Too many COO segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (179 ,' Too many DRU segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (180 ,' Too many OBS segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (181 ,' Too many PTT segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (182 ,' Too many PVD segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (183 ,' Too many REQ segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (184 ,' Too many RES segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (185 ,' Too many STS segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (186 ,' Too many UNA segments.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (187 ,' Too many COO element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (188 ,' Too many DRU element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (189 ,' Too many OBS element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (190 ,' Too many PTT element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (191 ,' Too many PVD element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (192 ,' Too many REQ element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (193 ,' Too many RES element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (194 ,' Too many STS element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (195 ,' Too many UIB element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (196 ,' Too many UIH element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (197 ,' Too many UIT element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (198 ,' Too many UIZ element repetitions.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (199 ,' Segment count mismatch in UIT.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (200 ,' Message missing required REQ segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (201 ,' Message missing required RES segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (202 ,' Message missing required STS segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (203 ,' Message missing required PVD segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (204 ,' Message missing required PTT segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (205 ,' Message missing required COO segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (206 ,' Message missing required DRU segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (207 ,' Message missing required OBS segment.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (208 ,' Sender no longer active.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (209 ,' Receiver no longer active.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (210 ,' Unable to process transaction. Please resubmit.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (211 ,' DUE Reason For Service Code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (212 ,' DUE Professional Service Code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (213 ,' DUE Result Of Service Code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (214 ,' DUE Co-Agent ID is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (215 ,' DUE Co-Agent ID Qualifier is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (216 ,' Drug Coverage Status Code is invalid.');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (217 ,' COO Date/Time/Period Expiration date of needed history is less than Effective Date(Begin) of needed history');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (218 ,' COO Patient Identifier is invalid');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (219 ,' COO Cannot process Medication History due to value of Condition/Response, coded (Patient Consent Indicator)');
INSERT INTO surescripts.error_codes(error_code, error_desc) VALUES (220 ,' Message is a duplicate');
