INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('AL' ,'Alabama');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('AK' ,'Alaska');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('AZ' ,'Arizona');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('AR' ,'Arkansas');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('CA' ,'California');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('CO' ,'Colorado');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('CT' ,'Connecticut');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('DE' ,'Delaware');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('FL' ,'Florida');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('GA' ,'Georgia');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('HI' ,'Hawaii');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('ID' ,'Idaho');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('IL' ,'Illinois');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('IN' ,'Indiana');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('IA' ,'Iowa');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('KS' ,'Kansas');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('KY' ,'Kentucky');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('LA' ,'Louisiana');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('ME' ,'Maine');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('MD' ,'Maryland');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('MA' ,'Massachusetts');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('MI' ,'Michigan');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('MN' ,'Minnesota');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('MS' ,'Mississippi');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('MO' ,'Missouri');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('MT' ,'Montana');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('NE' ,'Nebraska');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('NV' ,'Nevada');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('NH' ,'New Hampshire');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('NJ' ,'New Jersey');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('NM' ,'New Mexico');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('NY' ,'New York');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('NC' ,'North Carolina');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('ND' ,'North Dakota');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('OH' ,'Ohio');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('OK' ,'Oklahoma');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('OR' ,'Oregon');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('PA' ,'Pennsylvania');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('RI' ,'Rhode Island');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('SC' ,'South Carolina');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('SD' ,'South Dakota');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('TN' ,'Tennessee');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('TX' ,'Texas');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('UT' ,'Utah');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('VT' ,'Vermont');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('VA' ,'Virginia');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('WA' ,'Washington');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('WV' ,'West Virginia');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('WI' ,'Wisconsin');
INSERT INTO surescripts.states_names(state_code, state_desc) VALUES ('WY' ,'Wyoming');
